/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List clients
         * @description Every client with billing profile, autonomy state, contract summary, unbilled exposure and invoice-history count.
         */
        get: operations["ClientsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Client detail
         * @description Full client detail: parsed contract with clauses, invoice history and unbilled exposure.
         */
        get: operations["ClientsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{id}/autonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle autonomy
         * @description Flip the per-client auto-send policy. ON lets Robyn send invoices without asking, within contract terms.
         */
        patch: operations["ClientsController_setAutonomy"];
        trace?: never;
    };
    "/clients/{id}/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get parsed contract
         * @description The contract on file with its parsed clauses for the clause viewer. Null if none is filed.
         */
        get: operations["ClientsController_getContract"];
        put?: never;
        /**
         * Attach / re-parse a contract
         * @description Parse pasted contract text into rate, terms and cited clauses, file it against the client, set the billing profile, and resolve any ATTACH_CONTRACT task.
         */
        post: operations["ClientsController_attachContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/potential-clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Potential-client queue
         * @description The pipeline rail: prospects seen on the calendar but not yet in Xero, with watch state and the agreement-evidence quote once found.
         */
        get: operations["PotentialClientsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/potential-clients/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm & promote a prospect
         * @description Loop-2 finish: create the Xero contact, create a real Client, raise ATTACH_CONTRACT and resolve the CONFIRM_AGREEMENT task. Xero failures are non-fatal — the prospect is still promoted locally.
         */
        post: operations["PotentialClientsController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/potential-clients/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss a prospect
         * @description Remove a prospect from the pipeline and resolve its CONFIRM_AGREEMENT task.
         */
        post: operations["PotentialClientsController_dismiss"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List meetings
         * @description All meetings with state, client, duration, attendees, transcript flag and linked proposal id.
         */
        get: operations["MeetingsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meeting detail
         * @description Full meeting with parsed transcript, match proposals, linked proposal and the evidence/decision chain.
         */
        get: operations["MeetingsController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync the calendar (check now)
         * @description Ingests the calendar (Google read-only if configured, else the seeded .ics fallback), upserts meetings and runs the Loop-1 step on every un-progressed meeting. Updates the CALENDAR connection state.
         */
        post: operations["MeetingsController_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/import-ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import an .ics calendar
         * @description Fallback ingest path: parse raw .ics text, upsert meetings and run the Loop-1 step.
         */
        post: operations["MeetingsController_importIcs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach a transcript
         * @description Saves and parses the transcript, resolves the PROVIDE_TRANSCRIPT task, then runs the Loop-1 continuation (match, price, policy, auto-send or raise REVIEW_INVOICE).
         */
        post: operations["MeetingsController_attachTranscript"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{id}/confirm-client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm the client for a meeting
         * @description Sets the client, resolves the CONFIRM_CLIENT_MATCH task and re-runs the proposal-building continuation.
         */
        post: operations["MeetingsController_confirmClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{id}/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Skip a meeting
         * @description Marks the meeting SKIPPED (not billable) and resolves any open transcript/match task.
         */
        post: operations["MeetingsController_skip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Poll the mailbox for client agreements (check now)
         * @description Reads NEW messages FROM queued/watching potential-client addresses ONLY (IMAP when configured, else the seeded fixture mailbox), classifies each for agreement, and on agreement flips the PotentialClient to AGREEMENT_DETECTED and raises a CONFIRM_AGREEMENT task. Never reads a non-queued sender; never promotes a client (that is ClientsModule).
         */
        post: operations["EmailController_poll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List invoice proposals
         * @description All proposals with client name, source (meeting/detection), totals, state, policy verdict and Xero link. Filter with ?state=.
         */
        get: operations["ProposalsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a proposal in full
         * @description Full lines with provenance chips, policy reasons, the source evidence chain (meeting/transcript/detection/contract) and live Xero status.
         */
        get: operations["ProposalsController_detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve and send the proposal to Xero
         * @description Writes an AUTHORISED ACCREC invoice (contact + invoice + decision note + evidence), sets state SENT, resolves the REVIEW_INVOICE task and marks the source meeting SENT. On Xero failure the proposal stays IN_REVIEW and the error is returned in the body (never a 500).
         */
        post: operations["ProposalsController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{id}/save-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a DRAFT invoice in Xero
         * @description Writes a DRAFT (unauthorised) ACCREC invoice to Xero and records its id + deep link, but keeps the proposal IN_REVIEW awaiting approval. On Xero failure the error is returned in the body (never a 500).
         */
        post: operations["ProposalsController_saveDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject the proposal
         * @description Sets state REJECTED, resolves the REVIEW_INVOICE task and records the reason on the audit trail.
         */
        post: operations["ProposalsController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proposals/{id}/lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit the proposal lines
         * @description Replaces the line set before approval and recomputes line amounts + subtotal, tax and total.
         */
        patch: operations["ProposalsController_patchLines"];
        trace?: never;
    };
    "/detections/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the ledger detectors (check now)
         * @description Runs three idempotent detectors — QUOTE_NOT_INVOICED, RETAINER_STOPPED and EXPENSE_NOT_RECHARGED. Reads Xero when it is live and falls back to local seed data otherwise (evidence.source records which path was used). New detections are deduped by a stable key, so re-running is safe. Returns the created rows plus counts.
         */
        post: operations["DetectionsController_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List ledger detections
         * @description All detections with type, matched client, recoverable value, evidence and state. Filter with ?state= and/or ?type=.
         */
        get: operations["DetectionsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detections/{id}/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn a detection into an invoice proposal
         * @description Builds a single-line InvoiceProposal (provenance LEDGER) from the detection, sets it IN_REVIEW with 20% UK VAT, flips the detection to PROPOSED and raises a REVIEW_INVOICE task. Nothing is written to Xero here — approval lives in ProposalsModule. Idempotent: re-proposing returns the existing proposal.
         */
        post: operations["DetectionsController_propose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/detections/{id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss a detection
         * @description Sets the detection DISMISSED and records the reason (optional) on the audit trail.
         */
        post: operations["DetectionsController_dismiss"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List OPEN tasks (the inbox), newest first, each enriched with card context. */
        get: operations["TasksController_listOpen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tasks (OPEN and RESOLVED); optional ?state= filter. */
        get: operations["TasksController_listAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OPEN task counts by type, for the inbox badges. */
        get: operations["TasksController_counts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List integration health
         * @description Three rows — XERO (probed live from Xero health), CALENDAR and EMAIL (read from their ConnectionState rows, DOWN if never run). Read-only: does not trigger any sync/poll job.
         */
        get: operations["ConnectionsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/xero/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-probe Xero health
         * @description Forces a fresh Xero health check, upserts the XERO ConnectionState row, records an audit event, and returns the refreshed row. The "check now" for Xero. Never throws when Xero is down — returns a DOWN row with the reason.
         */
        post: operations["ConnectionsController_recheckXero"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calendar-view feed
         * @description Colour-coded events for the calendar view. colorKey is derived from meeting state: billed=teal, proposal=amber, awaiting=amber-outline, unknown=purple, skipped/personal=gray. Optionally window by event start with from/to.
         */
        get: operations["DashboardController_calendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/leak-strip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recoverable-money strip
         * @description The "£X was walking away" strip: recoverable total plus a per-source breakdown across OPEN detections, IN_REVIEW proposals and unbilled meetings.
         */
        get: operations["DashboardController_leakStrip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit trail feed
         * @description The audit trail screen: every state change, Xero write, policy decision and poll, newest first.
         */
        get: operations["DashboardController_audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Headline stats
         * @description Open tasks, total unbilled £ across clients, invoices sent this month, and client count.
         */
        get: operations["DashboardController_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BillingProfileDto: {
            /**
             * @description Rate in the contract currency.
             * @example 150
             */
            rate: number | null;
            /**
             * @description Whether the rate is hourly, per-day or a fixed fee.
             * @example HOUR
             * @enum {string|null}
             */
            rateUnit: "HOUR" | "DAY" | "FIXED" | null;
            /**
             * @description ISO 4217 currency code.
             * @example GBP
             */
            currency: string;
            /**
             * @description Billing cadence, if known.
             * @example monthly retainer
             */
            cadence: string | null;
            /**
             * @description Payment terms.
             * @example Net 14
             */
            terms: string | null;
            /**
             * @description CONTRACT (parsed from a signed document) or INFERRED (from history).
             * @example CONTRACT
             * @enum {string}
             */
            source: "CONTRACT" | "INFERRED";
            /**
             * @description Human-readable citation for where these terms came from.
             * @example Clause 3.1
             */
            provenance: string;
        };
        ContractSummaryDto: {
            /**
             * @description Whether a parsed contract is on file for this client.
             * @example true
             */
            hasContract: boolean;
            /** @example Consulting Agreement 2026 */
            title: string | null;
            /** @example 150 */
            rate: number | null;
            /**
             * @example HOUR
             * @enum {string|null}
             */
            rateUnit: "HOUR" | "DAY" | "FIXED" | null;
            /** @example GBP */
            currency: string | null;
            /** @example Net 14 */
            terms: string | null;
            /**
             * @example CONTRACT
             * @enum {string|null}
             */
            source: "CONTRACT" | "INFERRED" | null;
        };
        ClientListItemDto: {
            /** Format: uuid */
            id: string;
            /** @example Fenwick Interiors */
            name: string;
            /**
             * @example [
             *       "ops@fenwick.co.uk"
             *     ]
             */
            emails: string[];
            /** @description Xero ContactID once created; null until then. */
            xeroContactId: string | null;
            /**
             * @description Per-client auto-send policy.
             * @example false
             */
            autonomyEnabled: boolean;
            billingProfile: components["schemas"]["BillingProfileDto"] | null;
            contract: components["schemas"]["ContractSummaryDto"];
            /**
             * @description Sum of DRAFT/IN_REVIEW proposal totals — money not yet invoiced.
             * @example 1200
             */
            unbilledExposureGbp: number;
            /**
             * @description Number of invoices sent for this client.
             * @example 6
             */
            invoiceHistoryCount: number;
        };
        ClauseDto: {
            /**
             * @description The clause reference.
             * @example Clause 3.1
             */
            ref: string;
            /** @example The Consultant shall be paid at a rate of GBP 150 per hour. */
            text: string;
        };
        ContractDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            clientId: string;
            /** @example Consulting Agreement 2026 */
            title: string | null;
            /**
             * @description Source file reference for the contract.
             * @example pasted-contract
             */
            fileRef: string;
            /** @description The raw contract text so the viewer can highlight in place. */
            rawText: string | null;
            /** @example 150 */
            rate: number | null;
            /**
             * @example HOUR
             * @enum {string|null}
             */
            rateUnit: "HOUR" | "DAY" | "FIXED" | null;
            /** @example GBP */
            currency: string;
            /** @example Net 14 */
            paymentTerms: string | null;
            /** @example Ongoing UX consulting on a time basis. */
            scopeSummary: string | null;
            /** @description Every parsed clause, each keeping its citation. */
            clauses: components["schemas"]["ClauseDto"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        InvoiceHistoryItemDto: {
            /** Format: uuid */
            id: string;
            /**
             * @example SENT
             * @enum {string}
             */
            state: "DRAFT" | "IN_REVIEW" | "APPROVED" | "SENT" | "REJECTED";
            /**
             * @description Invoice total (incl. tax).
             * @example 900
             */
            total: number;
            /** @example GBP */
            currency: string;
            /**
             * @description Idempotency reference used in Xero.
             * @example ROBYN-8f21ac3d
             */
            reference: string | null;
            /** @example INV-0042 */
            xeroInvoiceNumber: string | null;
            /** @description Deep-link into the Xero invoice, once written. */
            xeroDeepLink: string | null;
            /**
             * @description Whether Robyn sent this automatically (autonomy ON).
             * @example false
             */
            autoSent: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        ClientDetailDto: {
            /** Format: uuid */
            id: string;
            /** @example Fenwick Interiors */
            name: string;
            /**
             * @example [
             *       "ops@fenwick.co.uk"
             *     ]
             */
            emails: string[];
            xeroContactId: string | null;
            /** @example false */
            autonomyEnabled: boolean;
            billingProfile: components["schemas"]["BillingProfileDto"] | null;
            /** @description The parsed contract on file, if any. */
            contract: components["schemas"]["ContractDto"] | null;
            /** @description Invoices sent for this client, newest first. */
            invoiceHistory: components["schemas"]["InvoiceHistoryItemDto"][];
            /** @example 1200 */
            unbilledExposureGbp: number;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateAutonomyDto: {
            /**
             * @description When true, Robyn may auto-send invoices for this client within contract terms. Default policy is OFF.
             * @example true
             */
            enabled: boolean;
        };
        UpsertContractDto: {
            /**
             * @description Human title for the contract (used as the file reference and card heading).
             * @example Fenwick Interiors — Consulting Agreement 2026
             */
            title?: string;
            /**
             * @description The full contract text. Robyn parses the rate, terms and clauses from this, citing each value back to its clause.
             * @example Clause 3.1 The Consultant shall be paid at a rate of GBP 150 per hour. Clause 5 Payment terms are Net 14.
             */
            rawText: string;
        };
        PotentialClientDto: {
            /** Format: uuid */
            id: string;
            /** @example Priya Nair */
            displayName: string;
            /**
             * @example [
             *       "priya.nair@gmail.com"
             *     ]
             */
            emails: string[];
            /**
             * @example QUEUED
             * @enum {string}
             */
            state: "QUEUED" | "WATCHING" | "AGREEMENT_DETECTED" | "PROMOTED" | "DISMISSED";
            /**
             * Format: uuid
             * @description The meeting this prospect was first seen on.
             */
            firstSeenMeetingId: string | null;
            /**
             * @description Verbatim agreement quote, once an agreement email is detected.
             * @example let's go ahead
             */
            evidenceQuote: string | null;
            /**
             * @description Sender of the agreement email, if detected.
             * @example priya.nair@gmail.com
             */
            evidenceFrom: string | null;
            /**
             * Format: uuid
             * @description Set to the new Client id once promoted.
             */
            promotedClientId: string | null;
            /**
             * Format: date-time
             * @description Last time Robyn polled this prospect's inbox.
             */
            lastPolledAt: string | null;
        };
        PromoteResultDto: {
            /**
             * Format: uuid
             * @description The id of the newly created Client.
             */
            clientId: string;
            /** @example Priya Nair */
            clientName: string;
            /** @description Xero ContactID if the write succeeded; null if Xero was unavailable. */
            xeroContactId: string | null;
            /**
             * @description True when a new Xero contact was created (false if reused or Xero down).
             * @example true
             */
            xeroContactCreated: boolean;
            /** @description Non-fatal Xero error message when the contact could not be created live. Local promotion still completed. */
            xeroError: string | null;
            /**
             * Format: uuid
             * @description The ATTACH_CONTRACT task raised for the new client.
             */
            attachContractTaskId: string | null;
            /** @description The prospect, now in PROMOTED state. */
            potentialClient: components["schemas"]["PotentialClientDto"];
        };
        DismissPotentialClientDto: {
            /**
             * @description Optional reason recorded on the audit trail for dismissing this prospect.
             * @example Not a real lead — internal calendar invite.
             */
            reason?: string;
        };
        /** @enum {string} */
        MeetingState: "DETECTED" | "AWAITING_TRANSCRIPT" | "TRANSCRIPT_ATTACHED" | "CLIENT_MATCHED" | "UNKNOWN_ATTENDEE" | "INVOICE_PROPOSED" | "SENT" | "SKIPPED";
        AttendeeDto: {
            /** @example jane@fenwick.co.uk */
            email: string;
            /** @example Jane Fenwick */
            name?: string;
            /** @example false */
            organizer?: boolean;
        };
        MeetingListItemDto: {
            id: string;
            gcalEventId: string;
            title: string;
            /** @description ISO timestamp. */
            start: string;
            /** @description ISO timestamp. */
            end: string;
            /** @example 1.5 */
            durationHours: number;
            state: components["schemas"]["MeetingState"];
            clientId?: Record<string, never> | null;
            clientName?: Record<string, never> | null;
            attendees: components["schemas"]["AttendeeDto"][];
            /** @description No external attendees — auto-skipped. */
            isPersonal: boolean;
            hasTranscript: boolean;
            /** @description Linked InvoiceProposal id, if any. */
            proposalId?: Record<string, never> | null;
            /**
             * @description 'google' | 'ics'
             * @example ics
             */
            source: string;
        };
        /** @enum {string} */
        TranscriptSource: "PASTED" | "GRANOLA" | "UPLOAD";
        ScopeItemDto: {
            description: string;
            /** @example 2 */
            est_hours: number;
            /** @description Verbatim transcript line evidencing the work. */
            evidence_quote: string;
            billable: boolean;
        };
        TranscriptParsedDto: {
            summary?: Record<string, never> | null;
            action_points: string[];
            scope_items: components["schemas"]["ScopeItemDto"][];
        };
        TranscriptDto: {
            id: string;
            source: components["schemas"]["TranscriptSource"];
            rawText: string;
            parsed?: components["schemas"]["TranscriptParsedDto"] | null;
        };
        MatchProposalDto: {
            client_id: string;
            client_name: string;
            /**
             * @description 0..1 confidence — a proposal, never a decision.
             * @example 0.82
             */
            confidence: number;
            reason: string;
        };
        /** @enum {string} */
        InvoiceProposalState: "DRAFT" | "IN_REVIEW" | "APPROVED" | "SENT" | "REJECTED";
        PolicyResultDto: {
            /** @description Whether Robyn may send without asking. */
            auto: boolean;
            /** @description Every reason the gate passed/failed. */
            reasons: string[];
        };
        /** @enum {string} */
        ProvenanceKind: "CONTRACT_CLAUSE" | "TRANSCRIPT_QUOTE" | "CALENDAR_BLOCK" | "LEDGER";
        LineProvenanceDto: {
            kind: components["schemas"]["ProvenanceKind"];
            /** @example Clause 3.1 */
            label: string;
            /** @example The Consultant shall be paid £150 per hour. */
            detail: string;
            /** @description Source id (meeting/contract/quote). */
            source_ref?: string;
        };
        ProposalLineDto: {
            description: string;
            /** @example 1.5 */
            quantity: number;
            /** @example 150 */
            unit_amount: number;
            /** @example 225 */
            line_amount: number;
            /** @example 200 */
            account_code?: string;
            /** @example OUTPUT2 */
            tax_type?: string;
            provenance: components["schemas"]["LineProvenanceDto"][];
        };
        MeetingProposalDto: {
            id: string;
            state: components["schemas"]["InvoiceProposalState"];
            /** @example ROBYN-1a2b3c4d */
            reference?: Record<string, never>;
            /** @example GBP */
            currency: string;
            /** @example 225 */
            subtotal: number;
            /** @example 45 */
            taxTotal: number;
            /** @example 270 */
            total: number;
            /** @description True if Robyn auto-sent it (autonomy ON). */
            autoSent: boolean;
            xeroInvoiceId?: Record<string, never> | null;
            xeroInvoiceNumber?: Record<string, never> | null;
            xeroDeepLink?: Record<string, never> | null;
            policyResult: components["schemas"]["PolicyResultDto"];
            lines: components["schemas"]["ProposalLineDto"][];
        };
        /** @enum {string} */
        AuditActor: "ROBYN" | "HUMAN" | "LLM" | "XERO" | "SYSTEM";
        AuditEventDto: {
            /**
             * Format: uuid
             * @description Audit event id.
             */
            id: string;
            /**
             * @description Who acted.
             * @enum {string}
             */
            actor: "ROBYN" | "HUMAN" | "LLM" | "XERO" | "SYSTEM";
            /**
             * @description Machine verb, e.g. "xero.invoice.created".
             * @example xero.invoice.created
             */
            action: string;
            /** @description Human sentence for the audit trail. */
            summary: string;
            /** @description Subject kind, e.g. "meeting" | "proposal" | "client". */
            subjectType: string | null;
            /**
             * Format: uuid
             * @description Subject id.
             */
            subjectId: string | null;
            /** @description The decision inputs kept so an auditor can reconstruct it. */
            inputs: {
                [key: string]: unknown;
            } | null;
            /** @description When it happened (ISO datetime). */
            createdAt: string;
        };
        MeetingDetailDto: {
            id: string;
            gcalEventId: string;
            title: string;
            /** @description ISO timestamp. */
            start: string;
            /** @description ISO timestamp. */
            end: string;
            /** @example 1.5 */
            durationHours: number;
            state: components["schemas"]["MeetingState"];
            clientId?: Record<string, never> | null;
            clientName?: Record<string, never> | null;
            attendees: components["schemas"]["AttendeeDto"][];
            /** @description No external attendees — auto-skipped. */
            isPersonal: boolean;
            hasTranscript: boolean;
            /** @description Linked InvoiceProposal id, if any. */
            proposalId?: Record<string, never> | null;
            /**
             * @description 'google' | 'ics'
             * @example ics
             */
            source: string;
            /** @description Reason the meeting was skipped. */
            skipReason?: Record<string, never> | null;
            transcript?: components["schemas"]["TranscriptDto"] | null;
            /** @description LLM fuzzy match proposals (only when unknown/ambiguous). */
            matchProposals?: components["schemas"]["MatchProposalDto"][] | null;
            proposal?: components["schemas"]["MeetingProposalDto"] | null;
            /** @description The evidence/decision chain, newest first. */
            auditTrail: components["schemas"]["AuditEventDto"][];
        };
        /** @enum {string} */
        ConnectionStatus: "LIVE" | "FALLBACK" | "DOWN";
        SyncResultDto: {
            /**
             * @description 'google' | 'ics'
             * @example ics
             */
            source: string;
            status: components["schemas"]["ConnectionStatus"];
            label?: Record<string, never> | null;
            detail?: Record<string, never> | null;
            /** @description New meetings created this run. */
            imported: number;
            /** @description Existing meetings refreshed this run. */
            updated: number;
            /** @description Meetings the Loop-1 step ran on this run. */
            processed: number;
            /** @description ISO timestamp of this sync. */
            lastSyncAt: string;
        };
        ImportIcsDto: {
            /** @description Raw .ics calendar text to ingest. */
            icsText: string;
        };
        AttachTranscriptDto: {
            /** @description The pasted / uploaded transcript text. */
            rawText: string;
            /** @default PASTED */
            source: components["schemas"]["TranscriptSource"];
        };
        MeetingActionResultDto: {
            meeting: components["schemas"]["MeetingDetailDto"];
            proposal?: components["schemas"]["MeetingProposalDto"] | null;
            /** @description Populated when an attempted Xero write failed (state kept locally). */
            xeroError?: Record<string, never> | null;
        };
        ConfirmClientDto: {
            /** @description The Client to bill this meeting to. */
            clientId: string;
        };
        SkipMeetingDto: {
            /** @description Why the meeting is not billable. */
            reason?: string;
        };
        DetectedAgreementDto: {
            /** @description PotentialClient id whose sender agreed. */
            potentialClientId: string;
            /** @description Display name of the prospective client. */
            displayName: string;
            /** @description Sender address the agreement came from. */
            from: string;
            /** @description Subject line of the agreeing email. */
            subject: string;
            /** @description Verbatim sentence evidencing the agreement. */
            quote: string;
            /** @description Id of the CONFIRM_AGREEMENT task raised (absent if one was already open). */
            taskId?: string;
        };
        EmailPollResultDto: {
            /**
             * @description LIVE = IMAP mailbox, FALLBACK = fixture mailbox, DOWN = IMAP configured but unreachable.
             * @enum {string}
             */
            mode: "LIVE" | "FALLBACK" | "DOWN";
            /** @description Human explanation of the mode/status. */
            detail: string;
            /** @description Number of QUEUED/WATCHING potential clients polled. */
            polledCount: number;
            /** @description Number of new messages read from queued senders only. */
            messagesRead: number;
            /** @description Number of potential clients moved to AGREEMENT_DETECTED this poll. */
            agreementsDetected: number;
            /** @description Number of new CONFIRM_AGREEMENT tasks raised this poll. */
            tasksRaised: number;
            /** @description The agreements detected on this poll. */
            detected: components["schemas"]["DetectedAgreementDto"][];
            /** @description When this poll ran (ISO 8601). */
            polledAt: string;
            /** @description When the next scheduled poll is due (ISO 8601, now + 30m). */
            nextPollAt: string;
        };
        ProposalSummaryDto: {
            id: string;
            clientId: string;
            /** @description Resolved client display name */
            clientName: string;
            /**
             * @description What this proposal was built from
             * @enum {string}
             */
            source: "meeting" | "detection";
            /** @description Source meeting id, if any */
            meetingId?: Record<string, never> | null;
            /** @description Source detection id, if any */
            detectionId?: Record<string, never> | null;
            /** @example GBP */
            currency: string;
            /** @example 225 */
            subtotal: number;
            /** @example 45 */
            taxTotal: number;
            /** @example 270 */
            total: number;
            /** @enum {string} */
            state: "DRAFT" | "IN_REVIEW" | "APPROVED" | "SENT" | "REJECTED";
            policyResult: components["schemas"]["PolicyResultDto"];
            /** @description Number of invoice lines */
            lineCount: number;
            /** @description Whether Robyn auto-sent this (autonomy ON) */
            autoSent: boolean;
            /** @description Idempotency reference used in Xero */
            reference?: Record<string, never> | null;
            xeroInvoiceId?: Record<string, never> | null;
            xeroInvoiceNumber?: Record<string, never> | null;
            /** @description Deep link into the Xero UI */
            xeroDeepLink?: Record<string, never> | null;
            /** @description ISO created timestamp */
            createdAt: string;
        };
        ProposalEvidenceMeetingDto: {
            id: string;
            title: string;
            /** @description ISO start */
            start: string;
            /** @description ISO end */
            end: string;
            durationHours: number;
            state: string;
            /** @description Attendee emails */
            attendees: string[];
        };
        ProposalEvidenceTranscriptDto: {
            id: string;
            summary?: Record<string, never> | null;
            /** @description Verbatim billable-scope quotes */
            scopeQuotes: string[];
            /** @description Short raw excerpt for the drill-down */
            excerpt: string;
        };
        ProposalEvidenceDetectionDto: {
            id: string;
            type: string;
            valueGbp: number;
            /** @description Detector evidence summary */
            summary: string;
        };
        ProposalEvidenceContractDto: {
            contractId: string;
            clauseLabel?: Record<string, never> | null;
            /** @description Verbatim clause text */
            clauseText?: Record<string, never> | null;
        };
        ProposalEvidenceDto: {
            meeting?: components["schemas"]["ProposalEvidenceMeetingDto"] | null;
            transcript?: components["schemas"]["ProposalEvidenceTranscriptDto"] | null;
            detection?: components["schemas"]["ProposalEvidenceDetectionDto"] | null;
            contract?: components["schemas"]["ProposalEvidenceContractDto"] | null;
        };
        ProposalDetailDto: {
            id: string;
            clientId: string;
            /** @description Resolved client display name */
            clientName: string;
            /**
             * @description What this proposal was built from
             * @enum {string}
             */
            source: "meeting" | "detection";
            /** @description Source meeting id, if any */
            meetingId?: Record<string, never> | null;
            /** @description Source detection id, if any */
            detectionId?: Record<string, never> | null;
            /** @example GBP */
            currency: string;
            /** @example 225 */
            subtotal: number;
            /** @example 45 */
            taxTotal: number;
            /** @example 270 */
            total: number;
            /** @enum {string} */
            state: "DRAFT" | "IN_REVIEW" | "APPROVED" | "SENT" | "REJECTED";
            policyResult: components["schemas"]["PolicyResultDto"];
            /** @description Number of invoice lines */
            lineCount: number;
            /** @description Whether Robyn auto-sent this (autonomy ON) */
            autoSent: boolean;
            /** @description Idempotency reference used in Xero */
            reference?: Record<string, never> | null;
            xeroInvoiceId?: Record<string, never> | null;
            xeroInvoiceNumber?: Record<string, never> | null;
            /** @description Deep link into the Xero UI */
            xeroDeepLink?: Record<string, never> | null;
            /** @description ISO created timestamp */
            createdAt: string;
            lines: components["schemas"]["ProposalLineDto"][];
            evidence: components["schemas"]["ProposalEvidenceDto"];
            /** @description Live Xero status (DRAFT/AUTHORISED/...) if written */
            xeroStatus?: Record<string, never> | null;
            /** @description Last Xero write error, if the write failed */
            xeroError?: Record<string, never> | null;
        };
        ProposalActionResultDto: {
            id: string;
            /** @enum {string} */
            state: "DRAFT" | "IN_REVIEW" | "APPROVED" | "SENT" | "REJECTED";
            /** @description Did the Xero write succeed? */
            xeroWritten: boolean;
            xeroInvoiceId?: Record<string, never> | null;
            xeroInvoiceNumber?: Record<string, never> | null;
            xeroDeepLink?: Record<string, never> | null;
            /** @description Xero error message when the write failed */
            xeroError?: Record<string, never> | null;
            /** @example 225 */
            subtotal: number;
            /** @example 45 */
            taxTotal: number;
            /** @example 270 */
            total: number;
            /** @description Human sentence describing what happened */
            message: string;
        };
        RejectProposalDto: {
            /**
             * @description Why the proposal was rejected (kept on the audit trail)
             * @example Client already paid this in cash — do not invoice.
             */
            reason: string;
        };
        PatchLinesDto: {
            /** @description The full edited line set */
            lines: components["schemas"]["ProposalLineDto"][];
        };
        DetectionTypeCountsDto: {
            /** @example 1 */
            QUOTE_NOT_INVOICED: number;
            /** @example 1 */
            RETAINER_STOPPED: number;
            /** @example 1 */
            EXPENSE_NOT_RECHARGED: number;
        };
        DetectionDto: {
            id: string;
            /** @enum {string} */
            type: "QUOTE_NOT_INVOICED" | "RETAINER_STOPPED" | "EXPENSE_NOT_RECHARGED";
            /** @description Matched client id, if resolved */
            clientId?: Record<string, never> | null;
            /** @description Resolved client display name */
            clientName: string;
            /**
             * @description Recoverable value in GBP
             * @example 4200
             */
            valueGbp: number;
            /** @description Human explanation of the leak (from evidence.summary) */
            summary: string;
            /**
             * @description Which data path produced this detection
             * @enum {string}
             */
            source: "xero" | "local";
            /** @description Flexible per-detector evidence blob (always includes summary + source) */
            evidence: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            state: "OPEN" | "PROPOSED" | "RESOLVED" | "DISMISSED";
            /** @description Proposal built from this detection, if any */
            proposalId?: Record<string, never> | null;
            /** @description Xero invoice id once invoiced */
            xeroInvoiceId?: Record<string, never> | null;
            /** @description ISO created timestamp */
            createdAt: string;
        };
        RunDetectorsResultDto: {
            /**
             * @description Primary data path used this run
             * @enum {string}
             */
            source: "xero" | "local" | "mixed";
            /** @description Number of NEW detections created this run */
            created: number;
            /** @description Candidates skipped because a detection already existed (idempotent) */
            skipped: number;
            /** @description Newly created, by detector type */
            counts: components["schemas"]["DetectionTypeCountsDto"];
            /** @description The detections created this run */
            detections: components["schemas"]["DetectionDto"][];
            /** @description ISO timestamp of this run */
            ranAt: string;
            /** @description Human sentence describing what happened */
            message: string;
        };
        DetectionProposeResultDto: {
            detectionId: string;
            /** @enum {string} */
            detectionState: "OPEN" | "PROPOSED" | "RESOLVED" | "DISMISSED";
            /** @description The invoice proposal built from this detection */
            proposalId: string;
            /** @description Idempotency reference used in Xero */
            proposalReference?: Record<string, never> | null;
            /** @example 4200 */
            subtotal: number;
            /** @example 840 */
            taxTotal: number;
            /** @example 5040 */
            total: number;
            /** @description The REVIEW_INVOICE task raised for the human */
            taskId?: Record<string, never> | null;
            /** @description Human sentence describing what happened */
            message: string;
        };
        DismissDetectionDto: {
            /**
             * @description Why the detection was dismissed (kept on the audit trail)
             * @example Client was billed for this separately in cash.
             */
            reason?: string;
        };
        DetectionActionResultDto: {
            id: string;
            /** @enum {string} */
            state: "OPEN" | "PROPOSED" | "RESOLVED" | "DISMISSED";
            /** @description Human sentence describing what happened */
            message: string;
        };
        TaskDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "PROVIDE_TRANSCRIPT" | "CONFIRM_CLIENT_MATCH" | "REVIEW_INVOICE" | "CONFIRM_AGREEMENT" | "ATTACH_CONTRACT";
            /** @enum {string} */
            refType: "MEETING" | "PROPOSAL" | "POTENTIAL_CLIENT" | "CLIENT" | "DETECTION";
            /**
             * Format: uuid
             * @description Id of the referenced subject (meeting, proposal, ...)
             */
            refId: string;
            /** @enum {string} */
            state: "OPEN" | "RESOLVED";
            title: string;
            summary?: Record<string, never> | null;
            /** @description Free-form card context (client name, amount, quote, ...). Includes an `action` { method, path } hint when derivable. */
            context?: {
                [key: string]: unknown;
            } | null;
            /** @description Set once resolved by the owning module. */
            resolution?: Record<string, never> | null;
            /** Format: date-time */
            resolvedAt?: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        TaskTypeCountDto: {
            /** @enum {string} */
            type: "PROVIDE_TRANSCRIPT" | "CONFIRM_CLIENT_MATCH" | "REVIEW_INVOICE" | "CONFIRM_AGREEMENT" | "ATTACH_CONTRACT";
            /** @description Number of OPEN tasks of this type. */
            count: number;
        };
        TaskCountsDto: {
            /** @description Total OPEN tasks. */
            total: number;
            byType: components["schemas"]["TaskTypeCountDto"][];
        };
        ConnectionRowDto: {
            /**
             * @description Which integration this row describes.
             * @example XERO
             * @enum {string}
             */
            kind: "XERO" | "CALENDAR" | "EMAIL";
            /**
             * @description LIVE (real credentials working), FALLBACK (running on seed/fixtures), or DOWN (not connected / never run).
             * @example LIVE
             * @enum {string}
             */
            status: "LIVE" | "FALLBACK" | "DOWN";
            /**
             * @description Short label: org name, mailbox address, or calendar id.
             * @example Robyn Demo Co
             */
            label: string | null;
            /**
             * @description Human explanation of the current status (e.g. the reason a connection is DOWN).
             * @example Connected via Custom Connection.
             */
            detail: string | null;
            /**
             * Format: date-time
             * @description ISO timestamp of the last successful sync/probe for this integration.
             * @example 2026-07-04T10:15:00.000Z
             */
            lastSyncAt: string | null;
            /**
             * Format: date-time
             * @description ISO timestamp of the next scheduled poll (EMAIL cron), if any.
             * @example 2026-07-04T10:45:00.000Z
             */
            nextPollAt: string | null;
        };
        CalendarEventDto: {
            /**
             * Format: uuid
             * @description Meeting id.
             */
            id: string;
            /** @description Event title from the calendar. */
            title: string;
            /** @description Event start (ISO datetime). */
            start: string;
            /** @description Event end (ISO datetime). */
            end: string;
            /**
             * @description The meeting state driving the colour.
             * @enum {string}
             */
            state: "DETECTED" | "AWAITING_TRANSCRIPT" | "TRANSCRIPT_ATTACHED" | "CLIENT_MATCHED" | "UNKNOWN_ATTENDEE" | "INVOICE_PROPOSED" | "SENT" | "SKIPPED";
            /**
             * @description Colour token for the calendar view. billed=teal, proposal=amber, awaiting=amber-outline, unknown=purple, skipped/personal=gray.
             * @enum {string}
             */
            colorKey: "teal" | "amber" | "amber-outline" | "purple" | "gray";
            /** @description Matched client name, or null when unmatched/unknown. */
            clientName: string | null;
            /**
             * Format: uuid
             * @description Linked invoice proposal id if one exists for this meeting, else null.
             */
            proposalId: string | null;
        };
        LeakBreakdownDto: {
            /**
             * @description Human label for this leak source.
             * @example Invoices in review
             */
            source: string;
            /**
             * @description Recoverable amount (GBP, 2dp) attributable to this source.
             * @example 1440
             */
            gbp: number;
            /**
             * @description Number of items contributing to this source.
             * @example 2
             */
            count: number;
        };
        LeakStripDto: {
            /**
             * @description The month this leak strip summarises, e.g. "June 2026".
             * @example June 2026
             */
            monthLabel: string;
            /**
             * @description Total recoverable amount (GBP, 2dp): OPEN detections + IN_REVIEW proposals + unbilled meetings.
             * @example 2880
             */
            recoverableGbp: number;
            /** @description Per-source breakdown that sums to recoverableGbp. */
            breakdown: components["schemas"]["LeakBreakdownDto"][];
        };
        DashboardSummaryDto: {
            /**
             * @description Number of OPEN tasks in the inbox.
             * @example 3
             */
            openTasks: number;
            /**
             * @description Total unbilled exposure across all clients (GBP, 2dp).
             * @example 4200
             */
            unbilledGbp: number;
            /**
             * @description Invoice proposals sent to Xero so far this calendar month.
             * @example 1
             */
            invoicesSentThisMonth: number;
            /**
             * @description Number of clients.
             * @example 3
             */
            clientsCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ClientsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientListItemDto"][];
                };
            };
        };
    };
    ClientsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDetailDto"];
                };
            };
        };
    };
    ClientsController_setAutonomy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAutonomyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientListItemDto"];
                };
            };
        };
    };
    ClientsController_getContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractDto"];
                };
            };
        };
    };
    ClientsController_attachContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertContractDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractDto"];
                };
            };
        };
    };
    PotentialClientsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PotentialClientDto"][];
                };
            };
        };
    };
    PotentialClientsController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromoteResultDto"];
                };
            };
        };
    };
    PotentialClientsController_dismiss: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DismissPotentialClientDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PotentialClientDto"];
                };
            };
        };
    };
    MeetingsController_list: {
        parameters: {
            query?: {
                state?: "DETECTED" | "AWAITING_TRANSCRIPT" | "TRANSCRIPT_ATTACHED" | "CLIENT_MATCHED" | "UNKNOWN_ATTENDEE" | "INVOICE_PROPOSED" | "SENT" | "SKIPPED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingListItemDto"][];
                };
            };
        };
    };
    MeetingsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetailDto"];
                };
            };
        };
    };
    MeetingsController_sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultDto"];
                };
            };
        };
    };
    MeetingsController_importIcs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportIcsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResultDto"];
                };
            };
        };
    };
    MeetingsController_attachTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachTranscriptDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingActionResultDto"];
                };
            };
        };
    };
    MeetingsController_confirmClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmClientDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingActionResultDto"];
                };
            };
        };
    };
    MeetingsController_skip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Meeting id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipMeetingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetailDto"];
                };
            };
        };
    };
    EmailController_poll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailPollResultDto"];
                };
            };
        };
    };
    ProposalsController_list: {
        parameters: {
            query?: {
                state?: "DRAFT" | "IN_REVIEW" | "APPROVED" | "SENT" | "REJECTED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalSummaryDto"][];
                };
            };
        };
    };
    ProposalsController_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalDetailDto"];
                };
            };
        };
    };
    ProposalsController_approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalActionResultDto"];
                };
            };
        };
    };
    ProposalsController_saveDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalActionResultDto"];
                };
            };
        };
    };
    ProposalsController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectProposalDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalActionResultDto"];
                };
            };
        };
    };
    ProposalsController_patchLines: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchLinesDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalActionResultDto"];
                };
            };
        };
    };
    DetectionsController_run: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetectorsResultDto"];
                };
            };
        };
    };
    DetectionsController_list: {
        parameters: {
            query?: {
                state?: "OPEN" | "PROPOSED" | "RESOLVED" | "DISMISSED";
                type?: "QUOTE_NOT_INVOICED" | "RETAINER_STOPPED" | "EXPENSE_NOT_RECHARGED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionDto"][];
                };
            };
        };
    };
    DetectionsController_propose: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionProposeResultDto"];
                };
            };
        };
    };
    DetectionsController_dismiss: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DismissDetectionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionActionResultDto"];
                };
            };
        };
    };
    TasksController_listOpen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDto"][];
                };
            };
        };
    };
    TasksController_listAll: {
        parameters: {
            query?: {
                /** @description Filter by task state. Omit for all states. */
                state?: "OPEN" | "RESOLVED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDto"][];
                };
            };
        };
    };
    TasksController_counts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCountsDto"];
                };
            };
        };
    };
    ConnectionsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionRowDto"][];
                };
            };
        };
    };
    ConnectionsController_recheckXero: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionRowDto"];
                };
            };
        };
    };
    DashboardController_calendar: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound (ISO date/datetime) on the event start. Omit for no lower bound. */
                from?: string;
                /** @description Inclusive upper bound (ISO date/datetime) on the event start. Omit for no upper bound. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEventDto"][];
                };
            };
        };
    };
    DashboardController_leakStrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeakStripDto"];
                };
            };
        };
    };
    DashboardController_audit: {
        parameters: {
            query?: {
                /** @description Maximum number of audit events to return, newest first. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventDto"][];
                };
            };
        };
    };
    DashboardController_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryDto"];
                };
            };
        };
    };
}
