#!/usr/bin/env bash
# Claude Code Stop hook
# Extract the last assistant message from the transcript JSONL and write it to
# context/last_update.md, then commit to git.
set -euo pipefail

PAYLOAD=$(cat)
TRANSCRIPT_PATH=$(echo "$PAYLOAD" | jq -r '.transcript_path // empty')
CWD=$(echo "$PAYLOAD" | jq -r '.cwd // empty')
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$CWD}"
UPDATE_FILE="$PROJECT_DIR/context/last_update.md"

[[ -n "$TRANSCRIPT_PATH" && -f "$TRANSCRIPT_PATH" ]] || exit 0

LAST_TURN=$(
  jq -rs '
    map(select(.message.role == "assistant"))
    | last
    | (.message.content // "")
    | if type == "array"
      then map(select(.type == "text") | .text) | join("\n")
      else .
      end
  ' "$TRANSCRIPT_PATH" 2>/dev/null || true
)

[[ -n "$LAST_TURN" ]] || exit 0

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "$UPDATE_FILE" <<UPDATE_EOF
<!--
Cross-agent sync file. Auto-generated by hooks.
-->
agent: claude
timestamp: $TIMESTAMP

$LAST_TURN
UPDATE_EOF

cd "$PROJECT_DIR"
if git rev-parse --git-dir >/dev/null 2>&1; then
  git add -A >/dev/null 2>&1 || true
  if ! git diff --cached --quiet 2>/dev/null; then
    git commit -m "claude: turn @ $TIMESTAMP" >/dev/null 2>&1 || true
  fi
fi

exit 0
