#!/usr/bin/env bash
# Claude Code UserPromptSubmit hook
# If context/last_update.md has a recent entry from Cursor, print it to stdout
# (Claude Code injects stdout from this event as conversation context),
# then clear the file so it isn't re-injected.
set -euo pipefail

PAYLOAD=$(cat)
CWD=$(echo "$PAYLOAD" | jq -r '.cwd // empty')
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$CWD}"
UPDATE_FILE="$PROJECT_DIR/context/last_update.md"

[[ -f "$UPDATE_FILE" ]] || exit 0

if grep -q '^agent: cursor' "$UPDATE_FILE" 2>/dev/null; then
  echo "=== Cross-agent context (from Cursor's last turn) ==="
  sed '/^<!--/,/-->/d' "$UPDATE_FILE"
  echo "=== End cross-agent context ==="

  cat > "$UPDATE_FILE" <<'CLEAR_EOF'
<!--
Cross-agent sync file. Auto-generated by hooks.
-->
CLEAR_EOF
fi

exit 0
