#!/usr/bin/env bash
# Cursor afterAgentResponse hook
# Cursor passes the assistant's final text directly via .text. We write it to
# context/last_update.md tagged as 'cursor', then commit.
set -euo pipefail

PAYLOAD=$(cat)
WORKSPACE=$(echo "$PAYLOAD" | jq -r '.workspace_roots[0] // empty')
TEXT=$(echo "$PAYLOAD" | jq -r '.text // empty')
# Fall back to CURSOR_PROJECT_DIR env var if workspace_roots is empty
[[ -n "$WORKSPACE" ]] || WORKSPACE="${CURSOR_PROJECT_DIR:-}"
[[ -n "$WORKSPACE" ]] || exit 0
[[ -n "$TEXT" ]] || exit 0

UPDATE_FILE="$WORKSPACE/context/last_update.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "$UPDATE_FILE" <<UPDATE_EOF
<!--
Cross-agent sync file. Auto-generated by hooks.
-->
agent: cursor
timestamp: $TIMESTAMP

$TEXT
UPDATE_EOF

cd "$WORKSPACE"
if git rev-parse --git-dir >/dev/null 2>&1; then
  git add -A >/dev/null 2>&1 || true
  if ! git diff --cached --quiet 2>/dev/null; then
    git commit -m "cursor: turn @ $TIMESTAMP" >/dev/null 2>&1 || true
  fi
fi

exit 0
